version: '3'
services:
  mongo:
    restart: always
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
  auth:
    build:
      context: ./authService
    container_name: auth-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_PRIVATE_KEY_PATH=${JWT_PRIVATE_KEY_PATH}
      - JWT_PUBLIC_KEY_PATH=${JWT_PUBLIC_KEY_PATH}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongo
    networks:
      - app-network
  # general:
  #   build:
  #     context: ./generalService
  #   container_name: general-service
  #   restart: always
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - MONGO_URL=${MONGO_URL}
  #     - JWT_PUBLIC_KEY_PATH=${JWT_PUBLIC_KEY_PATH}
  #     - JWT_ALGORITHM=${JWT_ALGORITHM}
  #     - NODE_ENV=${NODE_ENV}
  #   depends_on:
  #     - mongo
  #     - auth
  #   networks:
  #     - app-network
  # front-end:
  #   build: 
  #     context: ./frontEnd
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   depends_on:
  #     - mongo
  #     - auth
  #     - general
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge